const res = {
    "trip_metrics": {
      "TRIP_TREND_TRIPS_PER_CAR": null,
      "TRIP_DIST_SCORE_BY_MILES_DRIVEN": null,
      "TRIP_OPT_IN_VEHICLES": null,
      "TOTAL_TRIP_COUNT": null,
      "TRIP_DIST_DRIVERS_BY_DAY_OF_WEEK": null,
      "AVG_TRIP_DURATION": null,
      "TRIP_FEATURE_USAGE": null,
      "TRIP_TREND_OVERALL_SCORES": null,
      "TRIP_DIST_DISTANCE_BY_DAY_OF_WEEK": null,
      "TRIP_DIST_TRIPS_PER_CAR_BY_HOUR_OF_DAY": null,
      "TRIPS_PER_VEHICLE": null,
      "TRIP_DIST_TRIPS_PER_CAR_BY_DAY_OF_WEEK": null,
      "TRIP_DIST_TRIPS_BY_DAY_OF_WEEK": null,
      "AVG_TRIP_DISTANCE": null,
      "AVG_TRIP_PER_CAR": null,
      "TRIP_REGISTERED_VEHICLES": null,
      "ACTIVE_USERS": null,
      "TRIP_DIST_DURATION_BY_DAY_OF_WEEK": null,
      "TRIP_DIST_SCORE_BY_TRIPS": null
    },
    "event_hub_metrics": {
      "SUCCESS_EVENT_COUNT": null,
      "ERROR_EVENT_COUNT": null,
      "DOMAIN_COUNT": null,
      "EVENT_TYPE_COUNT": null
    },
    "search_metrics": {
      "SEARCH_TOP_RESULT_STATE_SYSTEM": null,
      "ONEBOX_SEARCHS": null,
      "SEARCH_TREND_SEARCH_BY_CATEGORY": null,
      "SEARCH_ONEBOX_SEARCH": null,
      "SEARCH_TREND_SEARCH_REQUEST_FAILURE": null,
      "SEARCH_TREND_SEARCH_REQUEST": null,
      "SEARCH_RESPONSE_TIME_MAX": null,
      "SEARCH_RESPONSE_TIME_MIN": null,
      "SEARCH_RESPONSE_TIME_AVG": null,
      "SEARCH_TREND_ACTIVE_USERS": null,
      "SEARCH_ONEBOX_FILLRATE": null,
      "SEARCH_PER_VEHICLE": null,
      "SUGGESTION_TO_SEARCH": null,
      "SEARCH_TOTAL_TRIPS": null,
      "SEARCH_TO_DETAIL": null,
      "SEARCH_TREND_SEARCH_API": null,
      "SEARCH_CONNECTED_VEHICLES": null,
      "SEARCH_RESPONSE_TIME_90PERCENT": null,
      "SEARCH_COUNT_SEARCH": null,
      "SEARCH_ACTIVE_USERS": null,
      "SEARCH_TOP_RESULT_STATE_USER": null,
      "SEARCH_TREND_ONEBOX_SEARCHS": null,
      "SEARCH_TREND_SUGGESTION_API": null,
      "SEARCH_COUNT_SOURCE": null,
      "SEARCH_TREND_PREDICTED_DEST_SESSION": null,
      "SEARCH_TOP_RESULT_CATEGORY_SYSTEM": null,
      "SEARCH_TREND_ONEBOX_SEARCHS_FAILURE": null,
      "SEARCH_TOP_RESULT_CITY_SYSTEM": null,
      "SEARCH_RESPONSE_TIME_REQ_COUNT": null,
      "SEARCH_TREND_ONEBOX_SEARCH": null,
      "SEARCH_RESPONSE_TIME": null,
      "SEARCH_TREND_DETAIL_API": null,
      "SEARCH_COUNT_API": null,
      "ACTIVE_USERS": null,
      "SEARCH_TREND_ONEBOX_FILLRATE": null,
      "SEARCH_TOP_RESULT_KEYWORD": null,
      "SEARCH_PER_TRIP": null,
      "SEARCH_TREND_PLACE_DETAILS_WITH_TRIGGER": null,
      "SEARCH_TREND_ONEBOX_FILL_RATE": null,
      "SEARCH_TREND_ONEBOX_FAILURE": null,
      "SEARCH_TOP_RESULT_CATEGORY_USER": null,
      "SEARCH_TOP_RESULT": null,
      "ONEBOX_FILL_RATE": null,
      "SEARCH_COUNT": null,
      "SEARCH_TREND": null,
      "WORDPREDICTION_TO_SEARCH": null,
      "SEARCH_TOP_RESULT_CITY_USER": null,
      "SEARCH_TREND_ACTIVE_PREDICTED_DEST_SESSION": null
    },
    "product_metrics": {
      "LASTLOGSHEDACTIVITY": null,
      "OPTINVEHICLES": null,
      "AVGRESPONSETIME": null,
      "EFKHOMEPAGE": null,
      "TABLEAUREPORTS": null,
      "AVGTRIPDISTANCE": null,
      "PREDICTIONOPTIN": null,
      "VEHICLESWITHTRIPS": null,
      "APPACTIVATED": null,
      "ROUTESCREATED": null,
      "ETAACCURACY": null,
      "PREDICTIONENDEDINNAVSTART": null,
      "TOTAL_TRIPS": null,
      "ROUTETONAVSTART": null,
      "REGISTEREDUSERS": null,
      "NAVENDARRIVED": null,
      "TOTALTRIPS": null,
      "AVGTRIPDURATION": null,
      "LASTSEARCHACTIVITY": null,
      "SUPERSETLINK": null,
      "REGISTEREDVEHICLES": null,
      "LASTPREDICTIONACTIVITY": null,
      "TRIPSPERVEHICLE": null,
      "USERINTERACTEDPREDICTION": null,
      "TOTALPREDICTION": null,
      "DIAGNOSTICS": null
    },
    "home_area_metrics": {
      "HOMEAREA_TREND_SIZE_INCREASE": null,
      "AVG_HOMEAREA_SIZE": null,
      "HOMEAREA_CHANGE": null,
      "VEHICLE_CNT_W_DEF_HOMEAREA": null,
      "HOMEAREA_LOCATION_DIST": null,
      "HOMEAREA_TREND_SIZE_DECREASE": null,
      "HOMEAREA_SIZE_DIST": null,
      "HOMEAREA_TOP_CITY_USERS": null,
      "HOMEAREA_TREND_NEW_JOIN": null,
      "VEHICLE_CNT_W_HOMEAREA": null,
      "HOMEAREA_CONNECTED_VEHICLES": null,
      "TRIPS_IN_HOMEAREA": null,
      "HOMEAREA_TOP_CITY": null
    },
    "predictions_metrics": {
      "OPTIN_PREDICTION": null,
      "PREDICTION_ENDED_IN_NAVSTART": null,
      "PREDICTION_TREND_WORK": null,
      "USER_INTERACTED_PREDICTION": null,
      "PREDICTION_TREND_FIRST_AND_SECOND_CARD": null,
      "PREDICTION_TREND_SECOND_CARD": null,
      "PREDICTION_TREND_HOME": null,
      "LAST_ACTIVITY": null,
      "TOTAL_PREDICTION": null,
      "PREDICTION_TREND_FIRST_CARD": null,
      "PREDICTION_DESTINATION": null,
      "PREDICTION_ACCURACY": null,
      "PREDICTION_TREND_OTHERS": null
    },
    "tag_metrics": {},
    "nav_metrics": {
      "NAV_DIST_NAV_SESSIONS_BY_HOUR_OF_DAY": null,
      "NAV_DIST_NAV_SESSIONS_BY_DAY_OF_WEEK": null,
      "NAV_DIST_ARRIVED_ACTIVE_TRIP_USERS_BY_DATE": null,
      "NAV_TREND_NAV_ONEBOX_SEARCH_SESSION": null,
      "NAV_DIST_ARRIVED_TRIPS_BY_DATE": null,
      "NAV_TREND_ROUTE_SESSION": null,
      "NAV_ROUTE_DIST": null,
      "NAV_DIST_TOTAL_TRIPS_BY_DATE": null,
      "NAV_AVG_RESPONSE_TIME": null,
      "NAV_TREND_SEARCH_ONEBOX_SEARCH_SESSION": null,
      "NAV_TRIP_ETA_ACCURACY": null,
      "NAV_TREND_RESUMED_NAVSTART_SESSION": null,
      "NAV_DIST_TOTAL_ACTIVE_TRIP_USERS_BY_DATE": null,
      "NAV_END_DIST": null,
      "NAV_TREND_FREE_DRIVE_PER_TRIGGER_SESSION": null,
      "NAV_TOTAL_TRIPS": null,
      "NAV_TREND_ENGINE_ON_SESSION": null,
      "NAV_TREND_ACTIVE_NAV_SESSION": null,
      "NAV_APP_ACTIVATED": null,
      "NAV_ROUTE_ETA": null,
      "NAV_ROUTES_CREATED": null,
      "NAV_ROUTE_END": null,
      "NAV_TREND_ACTIVE_NAV_PER_TRIGGER_SESSION": null,
      "NAV_TREND_TOTAL_SESSION": null,
      "NAV_CONNECTED_VEHICLES": null,
      "NAV_TREND_FREE_DRIVE_SESSION": null,
      "NAV_START_DIST": null,
      "NAV_RESPONSE_TIME_DIST": null
    },
    "vehicle_metrics": {
      "VEHICLE_TREND_ADM_DOWNLOADER_DOWNLOAD": null,
      "VEHICLE_SOLD": null,
      "TOP_CITY_BY_CARS": null,
      "VEHICLE_TREND_OTHER_DOWNLOAD": null,
      "DATA_AVG_USAGE_PER_VEHICLE": null,
      "VEHICLE_TREND_CLOUD_ENTITY_SERVICE_UPLOAD": null,
      "VEHICLE_TREND_MAP_CONTENT_TRAFFIC_UPLOAD": null,
      "VEHICLE_TREND_STRM_LF_UPLOAD": null,
      "VEHICLE_TREND_USER_SERVICE_DOWNLOAD": null,
      "VEHICLE_TREND_MAP_CONTENT_DATA_STREAMING_DOWNLOAD": null,
      "VEHICLE_TREND_DATA_SENSE_BATCHING_UPLOAD": null,
      "OPT_IN_VEHICLES": null,
      "VEHICLE_TREND_CLOUD_ENTITY_SERVICE_DOWNLOAD": null,
      "VEHICLE_TREND_DATA_SENSE_BATCHING_DOWNLOAD": null,
      "VEHICLE_TREND_FTUE_BY_APP_VERSION": null,
      "VEHICLE_TREND_ADM_DOWNLOADER_UPLOAD": null,
      "VEHICLE_TREND_MAP_CONTENT_TRAFFIC_DOWNLOAD": null,
      "VEHICLE_TREND_CONNECTED_CAR_BY_APP_VERSION": null,
      "REGISTERED_VEHICLES": null,
      "VEHICLE_TREND_VIVID_NAV_HTTP_UPLOAD": null,
      "VEHICLE_TREND_ADM_CLIENT_UPLOAD": null,
      "VEHICLE_TREND_DIRECTION_SERVICE_DOWNLOAD": null,
      "VEHICLE_TREND_STRM_LF_DOWNLOAD": null,
      "VEHICLE_TREND_ACTIVE_CAR_BY_LOCATION": null,
      "VEHICLE_TREND_ADM_CLIENT_DOWNLOAD": null,
      "VEHICLE_TREND_DIRECTION_SERVICE_UPLOAD": null,
      "VEHICLE_TREND_DATA_SENSE_JSON_BATCHING_UPLOAD": null,
      "VEHICLE_TREND_STRM_RF_UPLOAD": null,
      "VEHICLE_TREND_STRM_META_DOWNLOAD": null,
      "VEHICLE_TREND_MAP_CONTENT_DATA_STREAMING_UPLOAD": null,
      "VEHICLE_TREND_STRM_RF_DOWNLOAD": null,
      "VEHICLE_TREND_VIVID_NAV_HTTP_DOWNLOAD": null,
      "VEHICLE_TREND_DATA_SENSE_JSON_BATCHING_DOWNLOAD": null,
      "VEHICLE_TREND_OTHER_UPLOAD": null,
      "VEHICLE_TREND_USER_SERVICE_UPLOAD": null,
      "VEHICLE_DISTRIBUTION": null,
      "VEHICLE_TREND_STRM_META_UPLOAD": null
    },
    "dashboard_metrics": {
      "EVENTHUB": null,
      "EVENTS_MAP": null,
      "VEHICLE": null,
      "SEARCH_USAGE": null,
      "TOOLBOX": null,
      "USER_OVERVIEW": null,
      "TRIPS": null,
      "NAV_USAGE": null,
      "PRODUCT_SUMMARY": null,
      "PREDICTION": null,
      "USER_RETENTION": null,
      "FUNNEL": null,
      "ROLE_MANAGEMENT": null,
      "PERMISSION_MANAGEMENT": null,
      "ETL": null,
      "DPCS": null,
      "HOMEAREA": null,
      "OTA": null,
      "RAW_LOGS_MAP": null
    },
    "user_metrics": {
      "USER_TRIP_SUMMARY": null,
      "USER_TRIP_OVERVIEW": null,
      "USER_DATAUSAGE": null,
      "USER_LIST": null,
      "USER_PROFILE": null,
      "USER_TRIP_TIMEBAR": null
    },
    "raw_log_metrics": {
      "RAWLOGS_TIME_DIST": null,
      "RAWLOGS_EVENT_NAME_DIST": null,
      "RAWLOGS_ADMIN_DIST": null,
      "RAWLOGS_JSON": null
    },
    "event_map_metrics": {
      "EVENT_RECENT_ACTIVITY": null,
      "EVENT_DIST_TILE": null,
      "EVENT_NAME_DIST": null,
      "EVENT_TIME_DIST": null,
      "EVENT_TRIGGER_DIST": null,
      "EVENT_DIST_GEOHASH": null,
      "EVENT_DIST_ADMIN": null
    },
    "etl_metrics": {
      "ETL_TREND_INPUT_SIZE": null,
      "SUCCESSFUL_TASK_COUNT": null,
      "AVG_INPUT_SIZE": null,
      "ETL_AGGR_STATUS": null,
      "ETL_TREND": null,
      "ETL_TREND_HEALTHY": null,
      "FAILED_TASK_COUNT": null,
      "ETL_TREND_ERROR": null,
      "AVG_PROCESSING_TIME": null,
      "ETL_LOOKUP_REQUEST": null,
      "ETL_STATUS": null,
      "ETL_TREND_OUTPUT_SIZE": null,
      "AVG_OUTPUT_SIZE": null
    },
    "funnel_metrics": {
      "FUNNEL_TREND_EVENT_NAME": null,
      "FUNNEL_LOOKUP": null,
      "FUNNEL_FLOW": null,
      "FUNNEL_TREND": null
    },
    "retention_metrics": {
      "RETENTION": null
    },
    "dpcs_metrics": {
      "DPCS_TREND": null,
      "AVG_DAILY_TASKS": null,
      "DPCS_LIST": null,
      "AVG_DAILY_PROCESSING_TIME": null,
      "AVG_DAILY_USERS": null
    },
    "ota_metrics": {
      "OTA_METRIC_STREAMING_CHECK": null,
      "OTA_METRIC_NEW_DATA_RECEIVED": null,
      "OTA_METRIC_VEHICLE_WITH_NO_DATA_CHANGE": null,
      "OTA_TREND_VEHICLE_WITH_STREAMING": null,
      "OTA_DIST_OTA_SIZE_PER_CONTENT": null,
      "OTA_TREND_NO_UPDATE": null,
      "OTA_TREND_STREAMING_DATA_USAGE": null,
      "OTA_METRIC_NO_DATA_CHANGE": null,
      "OTA_DIST_OTA_SIZE_PER_HOMEAREA_SIZE": null,
      "OTA_METRIC_VEHICLE_WITH_OTA_CHECK": null,
      "OTA_METRIC_VEHICLE_WITH_OTA_NEW_VERSION": null,
      "OTA_TREND_OTA_REQUEST": null,
      "OTA_TREND_HOMEAREA_DATA_USAGE": null,
      "OTA_METRIC_TRIP_PERCENTAGE_WITH_STREAMING_CHECK": null,
      "OTA_DIST_VEHICLE_CNT_PER_LOCATION": null,
      "OTA_TREND_UPDATE_RECEIVED": null,
      "OTA_TREND_TOTAL_VEHICLE": null,
      "OTA_METRIC_TRIP_CNT_PER_USER_REQ_STREAMING": null,
      "OTA_DIST_OTA_SIZE_PER_LOCATION": null,
      "OTA_DIST_VEHICLE_CNT_PER_CONTENT": null,
      "OTA_TREND_VEHICLE_WITH_OTA": null
    }
  }

   function removeDescriptions(dto) {
    return Object.entries(dto)
      .map(([group, permissions]) => ({
        [group]: Array.isArray(permissions) ? permissions : Object.keys(permissions),
      }))
      .reduce(
        (result, group) => ({
          ...result,
          ...group,
        }),
        [],
      );
  }

  function descriptions(dto) {
    return Object.entries(dto)
      .map(([group, permissions]) => ({
        [group]: Array.isArray(permissions) ? permissions : Object.keys(permissions),
      }))
  }
  console.log(removeDescriptions(res));
  // console.log(descriptions(res));